from django.urls import path
from django.views.decorators.cache import cache_page
from apps.houserent import views

urlpatterns = [
    path(
        "placements/",
        (views.PlacementListAPIView.as_view()),
        name="placement-list",
    ),
    path(
        "object_kinds/",
        (views.ObjectKindListAPIView.as_view()),
        name="object_kind-list",
    ),
    path(
        "object_types/",
        (views.ObjectTypeListAPIView.as_view()),
        name="object_types-list",
    ),
    path(
        "locations/facilities/",
        (views.LocationFacilityListAPIView.as_view()),
        name="locations-facilities-list",
    ),
    path(
        "objects/facilities/",
        (views.ObjectFacilityListAPIView.as_view()),
        name="objects-facilities-list",
    ),
    path(
        "locations/",
        (views.LocationListAPIView.as_view()),
        name="locations-list",
    ),
    path(
        "locations/<uuid:pk>/",
        (views.LocationDetailAPIView.as_view()),
        name="location",
    ),
    path(
        "locations/<uuid:location_id>/objects/",
        (views.LocationObjectListAPIView.as_view()),
        name="location-objects-list",
    ),
    path(
        "objects/<uuid:pk>/",
        (views.LocationObjectDetailAPIView.as_view()),
        name="location-objects-detail",
    ),
    path(
        "objects/<uuid:object_id>/delete",
        (views.LocationObjectDeleteAPIView.as_view()),
        name="location-objects-list-delete",
    ),
    path(
        "objects/create/",
        (views.LocationObjectCreateAPIView.as_view()),
        name="object-create",
    ),
    path(
        "objects/",
        (views.LocationObjectAPIView.as_view()),
        name="object-list",
    ),
    path(
        "objects/<uuid:object_id>/prices/",
        (views.ObjectPriceListAPIView.as_view()),
        name="location-objects-detail-prices",
    ),
    path(
        "objects/<uuid:object_id>/reviews/",
        (views.ObjectReviewListAPIView.as_view()),
        name="location-objects-detail-prices",
    ),
    path(
        "objects/<uuid:pk>/prices/<uuid:price_id>/delete/",
        (views.ObjectPriceDeleteAPIView.as_view()),
        name="location-objects-detail-prices-delete",
    ),
    path(
        "objects_check/",
        (views.ObjectCheckListAPIView.as_view()),
        name="objects-check-list",
    ),
    path(
        "reviews_check/",
        (views.ReviewCheckListAPIView.as_view()),
        name="reviews-check-list",
    ),
    path(
        "analytics/",
        (views.VendorAnalyticsAPIView.as_view()),
        name="vendor_analytics",
    ),
    path(
        "analytics/offers/",
        (views.VendorOffersAPIView.as_view()),
        name="vendor_offers_list",
    ),
]
